import type { Session } from "./types";

// Used only when the UI runs outside a Tauri webview (e.g. `pnpm dev` in a
// plain browser), so the interface is still explorable without a backend.
export const MOCK_SESSIONS: Session[] = [
  {
    id: "default",
    name: "(default)",
    provider: "custom",
    readOnly: true,
    health: "ok",
    email: "ada@personal.dev",
    signingKey: "",
    gitdir: "~  (unconditional [include])",
    host: "github.com",
    alias: "",
    sshUser: "git",
    keyPath: "~/.ssh/id_ed25519",
    problems: [],
  },
  {
    id: "work",
    name: "work",
    provider: "github",
    readOnly: false,
    health: "ok",
    email: "ada@acme.com",
    signingKey: "3AA5C34371567BD2",
    gitdir: "~/work/",
    host: "github.com",
    alias: "github.com-work",
    sshUser: "git",
    keyPath: "~/.ssh/id_ed25519_work",
    problems: [],
  },
  {
    id: "personal",
    name: "personal",
    provider: "github",
    readOnly: false,
    health: "ok",
    email: "ada@personal.dev",
    signingKey: "",
    gitdir: "~/dev/",
    host: "github.com",
    alias: "github.com-personal",
    sshUser: "git",
    keyPath: "~/.ssh/id_ed25519_personal",
    problems: [],
  },
  {
    id: "oss",
    name: "oss",
    provider: "gitlab",
    readOnly: false,
    health: "warn",
    email: "ada@fastmail.com",
    signingKey: "",
    gitdir: "~/oss/",
    host: "gitlab.com",
    alias: "gitlab.com-oss",
    sshUser: "git",
    keyPath: "~/.ssh/id_ed25519_oss",
    problems: [
      {
        tone: "warn",
        title: "Orphan includeIf — no matching identity file",
        detail: "includeIf gitdir:~/oss/ → ~/.gitconfig.oss (not found)",
        suggestion: "Recreate ~/.gitconfig.oss or repoint the includeIf path.",
      },
    ],
  },
  {
    id: "client",
    name: "client-x",
    provider: "bitbucket",
    readOnly: false,
    health: "error",
    email: "ada@contractor.io",
    signingKey: "",
    gitdir: "~/clients/x/",
    host: "bitbucket.org",
    alias: "bitbucket.org-client-x",
    sshUser: "git",
    keyPath: "~/.ssh/id_ed25519_client",
    problems: [
      {
        tone: "error",
        title: "IdentityFile missing on disk",
        detail: "~/.ssh/id_ed25519_client",
        suggestion: "Generate a new key or point IdentityFile at an existing id_*.",
      },
      {
        tone: "warn",
        title: "Host block not correlated to any identity",
        detail: "Host bitbucket.org-client-x in ~/.ssh/config",
        suggestion: "Add a matching [url] insteadOf, or delete the stale Host block.",
      },
    ],
  },
];

export const MOCK_EXISTING_KEYS = ["~/.ssh/id_ed25519", "~/.ssh/id_ed25519_work", "~/.ssh/id_ed25519_personal", "~/.ssh/id_rsa"];
